services:
  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - healthcare-network
  migration:
    build: .
    volumes:
      - csv_data:/app/data
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017
    networks:
      - healthcare-network

volumes:
  mongo_data:
  csv_data:

networks:
  healthcare-network:
