services:
  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
  migration:
    build: .
    volumes:
      - csv_data:/app/data
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017
volumes:
  mongo_data:
  csv_data:
